[package]
name = "plain-rt"
version = "0.1.0"
authors = ["xiaopengli89 <x.friday@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
